---
homeassistant:
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret httppw

http:
  ssl_certificate: !secret ssl_crt
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.2.1.0/24

frontend:
  themes: !include_dir_merge_named themes

logger:
  default: info

# default_config:
bluetooth:
cloud:
config:
counter:
dhcp:
# energy:
hardware:
history:
homeassistant_alerts:
image:
input_boolean:
input_button:
input_datetime:
input_number:
input_select:
input_text:
logbook:
map:
media_source:
mobile_app:
my:
person:
# stream:
ssdp:
sun:
system_health:
tag:
timer:
usb:
webhook:
zeroconf:
zone:

recorder:
  db_url: !secret mysql
  purge_keep_days: 30
  exclude:
    domains:
      - automation
      - weblink
      - group
    entities:
      - sun.sun
      - binary_sensor.remote_ui

automation: !include automations.yaml
# notify: !include notify.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
# ecovacs: !include ecovacs.yaml
# image_processing: !include image_processing.yaml
# camera: !include cameras.yaml
