---
- platform: amazon_rekognition
  aws_access_key_id: !secret rekogkey
  aws_secret_access_key: !secret rekogsec
  region_name: us-east-1
  confidence: 90
  targets:
    - target: person
    - target: car
    - target: animal
    - target: pet
    - target: cat
    - target: dog
      confidence: 50
  # roi_x_min: 0.35
  roi_x_max: 0.8
  roi_y_min: 0.4
  roi_y_max: 0.8
  scale: 0.75
  save_file_format: png
  save_file_folder: /config/www/amazon-rekognition/
  save_timestamped_file: True
  always_save_latest_file: True
  source:
    - entity_id: camera.driveway

- platform: amazon_rekognition
  aws_access_key_id: !secret rekogkey
  aws_secret_access_key: !secret rekogsec
  region_name: us-east-1
  confidence: 90
  targets:
    - target: person
    - target: car
    - target: animal
    - target: pet
    - target: cat
    - target: dog
      confidence: 50
  # roi_x_min: 0.35
  roi_x_max: 0.8
  roi_y_min: 0.4
  roi_y_max: 0.8
  scale: 0.75
  save_file_format: png
  save_file_folder: /config/www/amazon-rekognition/
  save_timestamped_file: True
  always_save_latest_file: True
  source:
    - entity_id: camera.front_door_main
# - platform: platerecognizer
#   api_token: !secret plate
#   regions:
#     - us
#   save_file_folder: !secret plate_folder
#   save_timestamped_file: true
#   always_save_latest_file: true
#   source:
#     - entity_id: camera.deepstackobject
