---
- platform: deepstack_face
  ip_address: !secret deepstack_ip
  port: 8082
  api_key: !secret deepstack_api
  timeout: 5
  detect_only: false
  save_file_folder: !secret deepstack_save_folder
  save_timestamped_file: true
  save_faces: true
  save_faces_folder: !secret deepstack_face_folder
  show_boxes: true
  source:
    - entity_id: camera.front_door_main

- platform: deepstack_object
  ip_address: !secret deepstack_ip
  port: 8082
  api_key: !secret deepstack_api
  timeout: 5
  save_file_folder: !secret deepstack_save_folder
  save_timestamped_file: true
  always_save_latest_file: true
  show_boxes: true
  scale: 0.75
  # roi_x_min: 0.35
  roi_x_max: 0.8
  # roi_y_min: 0.4
  roi_y_max: 0.8
  crop_to_roi: true
  targets:
    - target: person
    - target: vehicle
      confidence: 60
    - target: car
      confidence: 60
  source:
    - entity_id: camera.driveway

- platform: platerecognizer
  api_token: !secret plate
  regions:
    - us
  save_file_folder: !secret plate_folder
  save_timestamped_file: true
  always_save_latest_file: true
  source:
    - entity_id: camera.deepstackobject
