---
- platform: rest  
  resource: https://api.ipgeolocation.io/astronomy?lat=39.46080703379273&long=-104.78879928588869&apiKey=ce1732bd24ed47738b7f54a656be9c99
  name: ip_geo_location
  scan_interval: 300
  value_template: "OK"
  json_attributes:
    - moonrise
    - moonset
    - moon_altitude
