substitutions:
  name: ratgdov25i-18fe0a
  friendly_name: Garage 2
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25iboard.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: POFmr6Xu2sBS70Bp9Xv9YphAtFgyEXBkSI8TfbUVxOM=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome