packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic-s3.yaml@main

esphome:
  name: stbp
  friendly_name: Salt Tank Sensor & Bluetooth Proxy
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "hh0HBObiHIIXVKpAsnzFG9amwXeWrPyxx3HQ6JPG6N0="

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  fast_connect: True

time:
  - platform: homeassistant
    id: homeassistant_time 

web_server:
  local: true

button:
  - platform: restart
    name: Restart

text_sensor:
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true

i2c:
  sda: GPIO16
  scl: GPIO17

sensor:
  - platform: vl53l0x
    name: "Salt Level"
    id: tof_softener_salt_level
    address: 0x29
    timeout: 60s
    update_interval: 300s
    unit_of_measurement: "m"
    filters:
      - filter_out: nan
      - median:
          window_size: 3
          send_first_at: 1
    accuracy_decimals: 2
    