esphome:
  name: salttank
  friendly_name: Salt Tank Level Sensor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "1xkrap24o2ugOA/AMeySktPFeFgN/rrtezH11oy2RWs="

ota:
  password: "86e8399ff971734354fac6b98b75aa3e"
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  fast_connect: True
  ap:
    ssid: "Salt-Tank"
    password: "1VyeJ1epu13V"

captive_portal:

web_server:
  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time 

button:
  - platform: restart
    name: restart

i2c:
  sda: GPIO16
  scl: GPIO17

sensor:
  - platform: vl53l0x
    name: "Salt Level"
    id: tof_softener_salt_level
    address: 0x29
    timeout: 60s
    update_interval: 1s
    unit_of_measurement: "m"
    filters:
      - filter_out: nan
      - median:
          window_size: 3
          send_first_at: 1
    accuracy_decimals: 2