substitutions:
  device_name: stbp
  device_id: stbp
  device_friendly_name: Salt Tank Sensor & Bluetooth Proxy
  device_sampling_time: 30s

packages:
  bluetooth-proxy: github://schettada/esphome/esp32-generic-s3.yaml@main
  sensors: github://schettada/esphome/sensors.yaml@main
  buttons: github://schettada/esphome/buttons.yaml@main

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1

# Enable Home Assistant API
api:
  encryption:
    key: "hh0HBObiHIIXVKpAsnzFG9amwXeWrPyxx3HQ6JPG6N0="

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  fast_connect: True

i2c:
  sda: GPIO16
  scl: GPIO17

sensor:
  - platform: vl53l0x
    name: "Salt Level"
    id: ${device_id}_salt_level
    address: 0x29
    timeout: 60s
    update_interval: 300s
    unit_of_measurement: "m"
    filters:
      - filter_out: nan
      - median:
          window_size: 3
          send_first_at: 1
    accuracy_decimals: 2
    