substitutions:
  name: tubeszb-cc2652-poe-2022
packages:
  tubezb.cc2652-poe-2022: github://tube0013/tube_gateways/models/current/tubeszb-cc2652-poe-2022/firmware/esphome/tubeszb-cc2652-poe-2022_v2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: Khc0x2pXDlDwuK4F9Z3c4jetmKw1u8D0AqOJhSpO2W8=

time:
  - platform: homeassistant
    id: homeassistant_time

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
