external_converters: []
devices:
  - devices.yaml
groups:
  - groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  #  server: mqtt://mqtt.nabucasa.io:1883
  user: "!secret zbuser"
  password: "!secret zbpass"
  client_id: zigbee2mqtt
  reject_unauthorized: true
serial:
  port: tcp://10.2.1.12:6638
advanced:
  log_level: debug
  pan_id: 6754
  channel: 25
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
